# Generated by Django 4.2.5 on 2023-10-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="bids_count",
        ),
    ]
