# Generated by Django 4.2.5 on 2023-10-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_bids_amount_bids_bidder_bids_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listings",
            old_name="price",
            new_name="list_price",
        ),
        migrations.RemoveField(
            model_name="listings",
            name="date_ending",
        ),
        migrations.AddField(
            model_name="listings",
            name="highest_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bids",
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUT", "Auto Parts"),
                    ("CLO", "Clothing, Shoes, Accessories"),
                    ("SPO", "Sporting Goods"),
                    ("TOY", "Toys"),
                    ("HOB", "Hobbies"),
                    ("HOM", "Home and Garden"),
                    ("JEW", "Jewelry and Watches"),
                    ("HEA", "Health and Beauty"),
                    ("IND", "Industrial"),
                    ("PET", "Pet Supplies"),
                    ("BAB", "Baby Essentials"),
                    ("ELE", "Electronics"),
                    ("COL", "Collectibles and Art"),
                    ("MED", "Books, Movies, Music"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
