# Generated by Django 4.2.5 on 2023-10-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_price_listings_list_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="text",
            field=models.TextField(default=" ", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bids",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="listings",
            name="description",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="listings",
            name="list_price",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="listings",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
