# Generated by Django 4.2.5 on 2023-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comments_text_comments_user_alter_bids_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
