# Generated by Django 4.2.5 on 2023-10-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_listings_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
            preserve_default=False,
        ),
    ]
