# Generated by Django 4.2.5 on 2023-10-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listings_winner_alter_listings_listed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to="auctions.listings"
            ),
        ),
    ]
