# Generated by Django 4.2.5 on 2023-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Auto Parts", "Auto"),
                    ("Clothing, Shoes, Accessories", "Clothing"),
                    ("Sporting Goods", "Sporting"),
                    ("Toys", "Toys"),
                    ("Hobbies", "Hobbies"),
                    ("Home and Garden", "Home"),
                    ("Jewelry and Watches", "Jewelry"),
                    ("Health and Beauty", "Health"),
                    ("Industrial", "Industrial"),
                    ("Pet Supplies", "Pet"),
                    ("Baby Essentials", "Baby"),
                    ("Electronics", "Electronics"),
                    ("Collectibles and Art", "Collectibles"),
                    ("Books, Movies, Music", "Media"),
                ],
                max_length=28,
                null=True,
            ),
        ),
    ]
