# Generated by Django 4.2.5 on 2023-11-08 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_following_like_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
