# Generated by Django 4.2.5 on 2023-11-10 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_following_followee_following_follower_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
