# Generated by Django 4.2.5 on 2023-11-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
